### ISSUE TITLE
Add ability to format currencies with 0 cents when no decimals provided

### ISSUE THREAD

**Issue by davehancock** [transferwise/formatting#17]
Bit of extra context / example case:

https://github.com/transferwise/comparison-components/pull/178

We'd ideally like to have the option to format [3] [GBP] as '3.00 GBP' instead of the current behaviour resulting in '3 GBP'.

Was / is it a conscious decision to omit the cents in all cases?

Based on the above I can either make this the default behaviour or add an option to format with cents.

**Comment by taaviaasver** [comment]
Did I understand correctly that you'd want to use `formatMoney`, and are passing in values like `3` and `4.56` and are expecting to always get 2 decimals, but currently getting `3 GBP` and `4.56 GBP`?

**Comment by davehancock** [comment]
Yes exactly.

Would like to have the cents included even if the decimal part is missing / partially included, e.g:

(Assume GBP)
`3`
`3.0`
`3.00`

should all format as:

`3.00 GBP`

**Comment by taaviaasver** [comment]
I think its fine that it omits trailing zeros by default, BUT `formatMoney` should accept `precision` like `formatNumber` does. Then you'd just do
```
formatMoney(amount, currency, locale, 2)
```
or even better if it would be
```
formatMoney(amount, currency, locale, { precision: 2 })
```

Also I must mention that I haven't been dealing with formatting money at all and have no strong opinions on this.

**Comment by davehancock** [comment]
The complexity with money might be that some currencies don't have cents and so you can't guarantee you'll get the precision you ask for.

Also its slightly more binary with currencies, either you show all cents or no cents in this case. You can't show 3 precision of cents and wouldn;t want to show only 1 decimal place.

**Comment by Tankenstein** [comment]
It was actually a conscious decision to format it that way. This is consistent with the way we do our formatting across platforms (iOS, android). If we want to change it again (it used to be the other way), we need to have a much wider discussion with designers and app devs.

**Comment by Tankenstein** [comment]
It was actually a conscious decision, used to be the other way before. I don't care too much either way but doing it this way will break consistency with the other platforms we're trying to get consistent with 😄, so it warrants wider discussion than this thread

Longer response in PR: https://github.com/transferwise/formatting/pull/18#pullrequestreview-206463764

**Comment by davehancock** [comment]
Ah ok, had a feeling there may be some historical context.

So this change doesn't change the defaults, in essence provides a way for someone to actively opt out.

For our use case in comparison, this will mean we can use transferwise/formatting and deprecate some other library we've been using for the exact same purpose. (Plus rate / amount formatting)

Agree should be a wider debate for general consistency, but for our specific case in our comparison table component we're pretty sure we'd want to have this formatted with the zero cents (as it is today on the current component). It's makes "scannability" much easier, or rather the lack of it makes it quite hard.

Would like to get this added as an optional opt soonish and concurrently debate for the wider side. Otherwise it blocks our adoption of this / deprecation of the other lib.
